### ISSUE TITLE
Cant seem to get a stream out of lazystream

### ISSUE THREAD

**Issue by Toylerrr** [taylorbourne/xteve_lazystream#73]
![image](https://user-images.githubusercontent.com/4400902/140596072-b5ed836f-25ab-4558-8ad3-a167e204bbc3.png)
I cant seem to get anything to stream to jellyfin 
Im using freesports.ddns for the host

**Comment by chanrwm** [comment]
Yea same issue after changing to 1.4 and the streamhost change. Some kind of decryption issue with that key file failure? I did try VLC and xTeVe instead of FFMPEG and that didn't help either.

**Comment by taylorbourne** [comment]
I can take a look this weekend but everything appears to be working on my end. 

When you set the variable did you restart your container?

**Comment by strenkml** [comment]
I had the same issue when I had the stream buffer set to FFmpeg.  When I switched it to xTeVe I stopped getting errors in the xTeVe log.

I am testing the stream in VLC with the link: "http://192.168.1.4:34400/m3u/xteve.m3u".

```
2021-11-06 15:56:43 [xTeVe] Buffer:                 true [xteve]

2021-11-06 15:56:43 [xTeVe] Buffer Size:            5120 KB

2021-11-06 15:56:43 [xTeVe] Channel Name:           Lazystream: NHL 1

2021-11-06 15:56:43 [xTeVe] Client User-Agent:      VLC/3.0.16 LibVLC/3.0.16

2021-11-06 15:56:44 [xTeVe] Streaming Status:       Playlist: nhl - Tuner: 1 / 2

2021-11-06 15:56:44 [xTeVe] Streaming Type:         [HLS / M3U8]

2021-11-06 15:56:44 [xTeVe] Streaming URL:          https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1636312803~acl=/*~id=nhlGatewayId:6352669~data=2026717681~hmac=2552c4b655ce4821cc882381445ab4a569a6ff1cfbd98d6831f4b64f26f4193e/5404665f72dd5b5c1368b315f2f8b3cb/va01/nhl/2021/11/06/NHL_GAME_VIDEO_TBLOTT_M2_HOME_20211106_1633976449229/master_wired60.m3u8

2021-11-06 15:56:44 [xTeVe] Streaming Status:       HTTP Response Status [200] OK

2021-11-06 15:56:44 [xTeVe] Content Type:           application/x-mpegURL

2021-11-06 15:56:44 [xTeVe] Streaming Status:       HTTP Response Status [200] OK

2021-11-06 15:56:44 [xTeVe] Content Type:           application/x-mpegURL

2021-11-06 15:56:44 [xTeVe] Streaming Status:       HTTP Response Status [200] OK

2021-11-06 15:56:44 [xTeVe] Content Type:           video/MP2T

```

I see the stream time increasing on VLC but nothing is played.  If I take the .m3u8 link from the log and try to play it directly, I dont get any playback.

**Comment by Toylerrr** [comment]
Got it fixed on my end it seems like its not wanting to set hosts via the cron job.

I fixed this by pinging freesports.ddns.net and getting the IP and adding this to the docker command/extra params:
--add-host=mf.svc.nhl.com:IP ADDRESS
--add-host=mlb-ws-mf.media.mlb.com:IP ADDRESS
--add-host=playback.svcs.mlb.com:IP ADDRESS

**Comment by SirRob24** [comment]
> Got it fixed on my end it seems like its not wanting to set hosts via the cron job.
> 
> I fixed this by pinging freesports.ddns.net and getting the IP and adding this to the docker command/extra params: --add-host=mf.svc.nhl.com:IP ADDRESS --add-host=mlb-ws-mf.media.mlb.com:IP ADDRESS --add-host=playback.svcs.mlb.com:IP ADDRESS

Sorry for being newb, but I am using Docker Desktop with Windows 10 so I'm not sure how/where to add these lines.

I have the issue where when I try to play a stream on Plex it fails to load and I get the "2021/11/06 16:46:32 [xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204"

**Comment by Toylerrr** [comment]
```
docker run -d \
	--name=xteve_lazystream \
	-p 34400:34400 \
	-e TZ="America/Los_Angeles" \
	--env-file=.env \
	--add-host=mf.svc.nhl.com:IP ADDRESS \
	--add-host=mlb-ws-mf.media.mlb.com:IP ADDRESS \
	--add-host=playback.svcs.mlb.com:IP ADDRESS \
	--log-opt max-size=10m \
	--log-opt max-file=3 \
	-v /mnt/user/appdata/xteve/.xteve:/xteve:rw \
	-v /mnt/user/appdata/xteve/config/:/config:rw \
	-v /mnt/user/appdata/xteve/guide2go/:/guide2go:rw \
	-v /mnt/user/appdata/xteve/playlists/:/playlists:rw \
	-v /tmp/xteve/:/tmp/xteve:rw \
	taylorbourne/xteve_lazystream
```

Make sure to change the args to fit your file system.

**Comment by chanrwm** [comment]
No dice after adding the host for me even after restarting the docker, still get that key error. I just added the one NHL host tho since I only have those channels mapped.

**Comment by taylorbourne** [comment]
Can you guys post some more logs? Specifically want to see when the container starts up and the hosts are set. It's possible I've garbled that line of shell but like I said, I had no problems on Thursday night running `1.4`.

**Comment by chanrwm** [comment]
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
GID/UID
-------------------------------------

User uid: 1000
User gid: 1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-install-defaults: executing...
[cont-init.d] 40-install-defaults: exited 0.
[cont-init.d] 50-update-hosts: executing...
[update-hosts] # Generated
[update-hosts] 127.0.0.1 Tower localhost
[update-hosts] 54.149.176.35 keys.lime-technology.com
[update-hosts] playback.svcs.mlb.com
[update-hosts] mf.svc.nhl.com
[update-hosts] mlb-ws-mf.media.mlb.com
[update-hosts] Processed 137 CA certificate(s).
[update-hosts] Resolving 'playback.svcs.mlb.com:443'...
[update-hosts] Connecting to '13.224.10.29:443'...
[update-hosts] - Certificate type: X.509
[update-hosts] - Got a certificate list of 2 certificates.
[update-hosts] - Certificate[0] info:
[update-hosts] - subject `CN=*.svcs.mlb.com,O=MLB Advanced Media, L.P.,L=New York,ST=New York,C=US', issuer `CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US', serial 0x0abac15da08e23c9cb0862c348b4f599, RSA key 2048 bits, signed using RSA-SHA256, activated `2021-01-14 00:00:00 UTC', expires `2022-01-18 23:59:59 UTC', pin-sha256="G+qJEzSuGRqBgoDnAR4B/lRQjioJEWyCHOkMD5BO7lM="
[update-hosts] Public Key ID:
[update-hosts] sha1:500ee3e0962ba80a096927a46801e64aed00e8d4
[update-hosts] sha256:1bea891334ae191a818280e7011e01fe54508e2a09116c821ce90c0f904eee53
[update-hosts] Public Key PIN:
[update-hosts] pin-sha256:G+qJEzSuGRqBgoDnAR4B/lRQjioJEWyCHOkMD5BO7lM=
[update-hosts]
[update-hosts] - Certificate[1] info:
Host playback.svcs.mlb.com (https) has never been contacted before.
Its certificate is valid for playback.svcs.mlb.com.
[update-hosts] - subject `CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US', issuer `CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US', serial 0x0a3508d55c292b017df8ad65c00ff7e4, RSA key 2048 bits, signed using RSA-SHA256, activated `2020-09-24 00:00:00 UTC', expires `2030-09-23 23:59:59 UTC', pin-sha256="RQeZkB42znUfsDIIFWIRiYEcKl7nHwNFwWCrnMMJbVc="
[update-hosts] - Status: The certificate is trusted.
[update-hosts] - Description: (TLS1.3-X.509)-(ECDHE-X25519)-(RSA-PSS-RSAE-SHA256)-(AES-128-GCM)
[update-hosts] - Session ID: 3F:A4:CB:F8:85:79:76:D1:D0:17:EA:6B:86:23:1E:C3:69:CA:D5:AD:0C:03:08:57:28:B1:B4:8C:99:86:0E:79
[update-hosts] - Options:
[update-hosts] - Handshake was completed
[update-hosts]
[update-hosts] - Simple Client Mode:
[update-hosts]
[update-hosts] - Peer has closed the GnuTLS connection
[update-hosts] Processed 137 CA certificate(s).
[update-hosts] Resolving 'mf.svc.nhl.com:443'...
[update-hosts] Connecting to '52.204.133.109:443'...
[update-hosts] - Certificate type: X.509
[update-hosts] - Got a certificate list of 4 certificates.
[update-hosts] - Certificate[0] info:
[update-hosts] - subject `CN=*.svc.nhl.com,OU=Cloud Account Management,O=BAMTECH, LLC,L=New York,ST=New York,C=US', issuer `CN=COMODO RSA Organization Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB', serial 0x00a11436fe0b7fba46c4a934df038e48a0, RSA key 2048 bits, signed using RSA-SHA256, activated `2021-05-25 00:00:00 UTC', expires `2022-05-25 23:59:59 UTC', pin-sha256="CD1201DANwCbi3gAjekhCcBJFBIYzdDWGkeMY4lG1gk="
[update-hosts] Public Key ID:
[update-hosts] sha1:57d6145cf1da6ec70b4f363a0225c5b2c6a03c82
[update-hosts] sha256:083d76d350c037009b8b78008de92109c049141218cdd0d61a478c638946d609
[update-hosts] Public Key PIN:
[update-hosts] pin-sha256:CD1201DANwCbi3gAjekhCcBJFBIYzdDWGkeMY4lG1gk=
[update-hosts]
[update-hosts] - Certificate[1] info:
Are you sure you want to trust it? (y/N): Host mf.svc.nhl.com (https) has never been contacted before.
Its certificate is valid for mf.svc.nhl.com.
[update-hosts] - subject `CN=COMODO RSA Organization Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB', issuer `CN=COMODO RSA Certification Authority,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB', serial 0x36825e7fb5a481937ef6d1736bb93ca6, RSA key 2048 bits, signed using RSA-SHA384, activated `2014-02-12 00:00:00 UTC', expires `2029-02-11 23:59:59 UTC', pin-sha256="EgNpQklEUNXn9Nl6RoIOC532j1g5+EFw0ZpLxxJq9Ms="
[update-hosts] - Certificate[2] info:
[update-hosts] - subject `CN=COMODO RSA Certification Authority,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB', issuer `CN=AAA Certificate Services,O=Comodo CA Limited,L=Salford,ST=Greater Manchester,C=GB', serial 0x67def43ef17bdae24ff5940606d2c084, RSA key 4096 bits, signed using RSA-SHA384, activated `2004-01-01 00:00:00 UTC', expires `2028-12-31 23:59:59 UTC', pin-sha256="grX4Ta9HpZx6tSHkmCrvpApTQGo67CYDnvprLg5yRME="
[update-hosts] - Certificate[3] info:
[update-hosts] - subject `CN=AAA Certificate Services,O=Comodo CA Limited,L=Salford,ST=Greater Manchester,C=GB', issuer `CN=AAA Certificate Services,O=Comodo CA Limited,L=Salford,ST=Greater Manchester,C=GB', serial 0x01, RSA key 2048 bits, signed using RSA-SHA1 (broken!), activated `2004-01-01 00:00:00 UTC', expires `2028-12-31 23:59:59 UTC', pin-sha256="vRU+17BDT2iGsXvOi76E7TQMcTLXAqj0+jGPdW7L1vM="
[update-hosts] - Status: The certificate is trusted.
[update-hosts] - Description: (TLS1.2-X.509)-(ECDHE-SECP256R1)-(RSA-SHA512)-(AES-128-GCM)
[update-hosts] - Session ID: 2C:97:8A:FB:0F:FA:1B:F4:5E:3E:02:57:57:48:C1:23:3E:2B:22:B4:97:D3:64:F3:5F:76:60:05:52:28:00:EA
[update-hosts] - Options: safe renegotiation,
[update-hosts] - Handshake was completed
[update-hosts]
[update-hosts] - Simple Client Mode:
[update-hosts]
[update-hosts] - Peer has closed the GnuTLS connection
[update-hosts] Processed 137 CA certificate(s).
Are you sure you want to trust it? (y/N): Cannot resolve mlb-ws-mf.media.mlb.com:443: Name does not resolve
[update-hosts] Resolving 'mlb-ws-mf.media.mlb.com:443'...
[update-hosts] |g0|playback.svcs.mlb.com|https|0|MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq1lZcwTOpxZtf3o5COa2ZaY/kT/QpFsnrJwAqtSeLmE5c2RmA3ELjHNcJXcNiw0cCoi/kVXWs41ycO32u42nxTgg0oWqeIDj+JC8Si3miO1jja8ZE07cqF8Mgba1/sr7Tc7ELKHfPo23nvAKqpVj4WpIvWnR021liIy8yraVhBVIzSdz/8/6Fogbwru/5lizieCvuzq7n4pjXeuUQSE/LccxG6RHb5wTNA4o2k+LvFXeqbHg8V6Pr1n74Y0dJnVozk7rnN8f2SRxdb5MoudEvRydw1B/XiI+mcP/M6w+34OmoVT+NPR06QZUNnxRepwH2wgKROHMmnNK+TEUs8YsUQIDAQAB
[cont-init.d] 50-update-hosts: exited 0.
[update-hosts] |g0|mf.svc.nhl.com|https|0|MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8VTq0OFO9tUVXIjg6jvFhkCJww5A0VTT6A9mILa2Luv/MG1Q6IjYXT8/esBnr0BFMIg2aZacSiGa1Xx5Eorpc0GFiw1dihY8L8ZJEkA/9whFSSkERiInyzQZ2TuMTnurhvThnp+G8GgSFDYdY7/LujPWRu3srQzPDRFLop1b02kBID9uaKBIK0IjJkWGaC3SPh/7WN3K+TBJlbg+tCkUXrUBMhuXOB0Tp8pCMbOfxQgawPMNO07e6JT9RQQQeyVPRjqimxVfNXy0ygcs9cjD1WN7F1g0fXaKJY9BxMnLaGkzMQj/KIfK1y+OchuAqAg3Jl9O9lrWer7IoS99kPc/7wIDAQAB
[cont-init.d] 60-update-lazystream: executing...
[update-lazystream] checking for update`

**Comment by taylorbourne** [comment]
Thank you!!

Going to try to take a look before tonight's games. In the event that I don't get to it, keep in mind you guys can downgrade to 1.3 at any time to use "that" host.

**Comment by strenkml** [comment]
> 
> 
> Thank you!!
> 
> Going to try to take a look before tonight's games. In the event that I don't get to it, keep in mind you guys can downgrade to 1.3 at any time to use "that" host.

I don't see a tag for 1.3 on Docker Hub, just 1.4 and 1.2.

Also the hosts fix from above did not fix my issue.

**Comment by taylorbourne** [comment]
@strenkml et al – please try the latest release (building now should be available in about 5 minutes as `1.5.0`)

**Comment by strenkml** [comment]
> 
> 
> @strenkml et al – please try the latest release (building now should be available in about 5 minutes as `1.5.0`)

The new build worked!  Thanks!

**Comment by taylorbourne** [comment]
Closing this – seems to be fixed with new builds
